# Generated by Django 2.1.3 on 2018-11-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_label', models.CharField(max_length=200)),
                ('article_sensor_no', models.IntegerField()),
                ('article_sensor_status', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_cost', models.IntegerField()),
                ('order_min', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('order_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('SensorNo', models.IntegerField(primary_key=True, serialize=False)),
                ('SensorStatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Supplier'),
        ),
        migrations.AddField(
            model_name='detail',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Supplier'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_supplier',
            field=models.ManyToManyField(to='tutorial.Supplier'),
        ),
    ]
